project:
  type: website

website:
  title: "Genética Molecular de Microrganismos"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - text: Slides
        menu:
          - href: slides/aula1.qmd
            text: Aula 1
      - text: Listas
        menu:
          - href: listas/lista1.qmd
            text: Lista 1
      - text: Leituras
        menu:
          - href: artigos/leitura1.pdf
            text: Artigo 1
  page-footer:
    center: "© 2025 Prof. Nome"

format:
  html:
    theme: cosmo
    toc: true