---
title: "02 - Grafos"
author: "Nicholas Barroso"
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    theme: cosmo
    code-copy: true
---

# Teoria de Grafos

**Primeiro, não confundir GRAFO com GRÁFICO.**

## Grafo versus Gráfico

**É possível andar pela cidade atravessando cada ponte exatamente uma vez?**

**Leonhard Euler**  
Matemático e físico Suíço  
Tentou responder a questão sobre as pontes de Kaliningrado.  
Para tanto desenvolveu a **Teoria dos Grafos**.

## Pontes de Kaliningrado

**É possível andar pela cidade atravessando cada ponte exatamente uma vez?**

## Grafo

### Definição 1
Um grafo é uma representação matemática de um objeto consistindo de **vértices (nós)** e **arestas** representando elementos e conexões, respectivamente.

**G = (V, E)**
O grafo G é um conjunto formado por um conjunto de vértices V e um conjunto de arestas E.

### Definição 2

**G = (V, E)**
O grafo G é um conjunto formado por um conjunto de vértices **V = {v₁, v₂, v₃, ..., vₙ}** e um conjunto de arestas **E = {(v₁, v₂), (v₃, vₙ), ..., (vₓ, v₂)}**.

### Definição 2 expandida

**G = (V, E)**
O grafo G é um conjunto formado por conjunto de vértices V e um conjunto de arestas E.  
Um grafo é uma representação matemática de um objeto consistindo de vértices (nós) e arestas representando elementos e conexões, respectivamente.

---

## Vértices ou nós
- São os elementos do grafo. Os elementos podem ser qualquer coisa:
  - Pessoas
  - Lugares
  - Genes
  - Animais
  - Proteínas
  - ...

## Arestas
As arestas indicam relações entre os elementos. O significado da relação pode mudar dependendo dos elementos.  
Por isso as arestas podem ser:

- **Não-direcionadas**: (v₁, v₂) = (v₂, v₁)  
  Quando a ligação não exibe precedência, somente relação.

- **Direcionadas**: (v₁, v₂) ≠ (v₂, v₁)  
  Quando a ligação entre os dados indica precedência ou ordem:
  - causa e efeito;
  - antes ou depois;
  - substrato → produto.

#### Arestas não-direcionadas
Relação sem precedência

#### Arestas direcionadas
Relação com precedência

**Por consequência:**
- Grafos com arestas direcionadas são **grafos direcionados**.
- Grafos com arestas não-direcionadas são **grafos não-direcionados**.

---

## Grafo conectado e não-conectado

- Um grafo não-direcionado é **conectado** quando possui pelo menos um vértice e existe um caminho entre cada par de vértices.
- Em um grafo conectado, não há vértices inacessíveis.
- Um grafo não direcionado que não está conectado é chamado **desconectado**.
- Um gráfico não direcionado G é, portanto, desconectado se existir dois vértices em G, de modo que nenhum caminho em G tenha esses vértices como pontos finais.
- Um grafo com apenas um vértice está conectado.
- Um gráfico sem arestas entre dois ou mais vértices é desconectado.

---

## Algumas definições

### Adjacência
Se os vértices compartilham da mesma aresta então eles são **adjacentes** entre si.

### Grau
O grau de um vértice é o número de arestas que incidem nele.

Exemplo:
3, 3, 2, 2

### Grau (grafos direcionados)
Para o grafo direcionado, o grau de vértice pode ser dividido em:
- **Grau de entrada**
- **Grau de saída**

Exemplo:  
3, 0, 1, 3, 1, 1, 1, 1

### Laço
Quando uma aresta começa e termina em um mesmo vértice ela é chamada de **laço** (loop).

### Layout
É a posição dos vértices e o desenho das arestas.

---

## Subgrafo

**G’ = (V’, E’)** onde V’ é um subconjunto de V e E’ é um subconjunto de E.  
Isso implica que E’ só possui arestas que começam e terminam em vértices que estão em V’.

### Subgrafo Induzido
Se G’ é um subgrafo de G e E’ possui **todas as arestas de E que ligam os vértices de V’**, então esse subgrafo é chamado de **grafo induzido**.

Exemplo:  
Vértices: 1, 2, 5, 7, 6, 3, 4  
E’ = {1,2; 5,6; 5,7}  
E’ = {1,2; 1,7; 5,5; 5,6; 5,7}

---

## Isomorfismo

Dois grafos G₁ e G₂ são **isomorfos** se existir um mapeamento bijetivo entre os vértices de V₁ e V₂ com a propriedade de que quaisquer dois vértices u, v ∊ V₁ são adjacentes se, e somente se, os dois vértices correspondentes no outro grafo também forem adjacentes.

**Traduzindo:** se um grafo possui os mesmo vértices que outro grafo e esses vértices mantém a adjacência nos dois grafos.

Exemplo:  
Vértices: 1, 2, 5, 3, 4

---

## Passeio & Caminho & Trilha

### Passeio (Walk)
Um passeio de distância k em um grafo é uma sequência alternante de vértices e arestas v₀, e₀, v₁, e₁, v₂, e₂, … , vₖ₋₁, eₖ₋₁, vₖ, que começa e termina em vértices.

### Caminho (Path)
Um caminho é um passeio no qual todos os vértices (exceto, possivelmente, o primeiro e o último) são distintos.

### Trilha ou Trajeto (Trail)
Trilha é um passeio onde todas as arestas são distintas.

---

## Caminhos especiais

### Caminho simples
Um caminho em que todos os vértices são diferentes.

### Caminho Euleriano
Um Caminho Euleriano é um caminho em um grafo que visita cada aresta apenas uma vez.

### Caminho Hamiltoniano
Um caminho hamiltoniano é um caminho que permite passar por todos os vértices de um grafo G, não repetindo nenhum, ou seja, passar por todos uma e uma só vez por cada.

---

## Comprimento e Ciclo

### Comprimento
É dado pelo número de arestas atravessadas de um vértice inicial a um vértice final.

### Ciclo
Um caminho em que o vértice de início e o vértice de término são o mesmo.

---

## Distância

A **distância** entre dois vértices é o comprimento do menor caminho entre eles ou ∞ se não existir um menor caminho.

### Menor caminho
É um caminho de tamanho mínimo entre dois vértices. Pode existir vários (passando por diferentes vértices) menores caminhos entre dois vértices.

Exemplo:  
Fazer a distância entre 6 e 2 passando por 5 e por 3.  
Depois fazer a distância entre 6 e 1 passando por 5 e por 3.

---

## Outros tipos de grafos

### Grafos Mistos
Um grafo que possui arestas direcionadas e não direcionadas.

### Multigrafo
É um grafo onde dois vértices podem ser ligados por mais de uma aresta.  
Nesse caso o pseudografo seria um grafo dirigido com pares de arestas paralelas dirigidas conectando cidades para mostrar que é possível voar para e a partir destas locações.

### Grafo Valorado ou Ponderado
São grafos nos quais as arestas possuem valores associados dando peso a cada conexão/interação.

### Hipergrafo
No hipergrafo, uma única aresta pode ligar mais de dois vértices.

### Grafos Bipartidos
Os hipergrafos podem ser representados por grafos bipartidos. Grafos bipartidos são aqueles que podem ser divididos em dois subgrafos disjuntos.

---

## Árvores

As árvores desempenham um papel importante na biologia, onde representam, por exemplo, as relações evolutivas entre as espécies como uma **árvore filogenética**.

- Uma **árvore** é um grafo acíclico conectado e não-direcionado.
- Os vértices de uma árvore com grau 1 são suas **folhas**.
- Todos os outros vértices são **vértices internos**.
- Uma **árvore enraizada** consiste de uma árvore G = (V, E) e um vértice distinto r ∈ V chamado de **raiz**.
- A **profundidade** de um vértice é o comprimento do caminho entre a raiz e este vértice.
- A **altura** de uma árvore é a profundidade máxima de um vértice.
- Uma **árvore binária** é uma árvore onde cada vértice tem no máximo grau 3.

---

## Representações de grafos

### Matriz de adjacência

Exemplo com vértices: 1, 2, 5, 4, 3, 6

### Lista de adjacência

Exemplo:
- = {1, 2, 5}
- = {1, 3, 5}
- = {2, 4}
- = {3, 5, 6}
- = {1, 2, 4}
- = {4}